baseURL = 'https://technoplasm.jp/'
languageCode = 'ja'
title = '株式会社テクノプラズム'

[params]
  description = 'テクノロジーで医療現場を支援する株式会社テクノプラズムのウェブサイトです'

[permalinks]
  blog = '/blog/:contentbasename/'
  news = '/news/:contentbasename/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
